services:
  am-32-ds:
    container_name: am-32-ds
    platform: linux/amd64
    build: .
    ports:
      - "3001:3001"
    environment:
      - TZ=America/New_York
      - VIRTUAL_ENV=/app/venv
      - npm_config_build_from_source=true
      - npm_config_arch=x64
      - npm_config_platform=linux
    volumes:
      - C:\Users\default.DESKTOP-1N8KV94\OneDrive\Renewal\Coding\dockerVolumes\dotenv\AM_3_2_DS:/app/.dotenv
      - C:\Users\default.DESKTOP-1N8KV94\OneDrive\Renewal\Coding\dockerVolumes\db:/app/database
    networks:
      - my-shared-network

networks:
  my-shared-network:
    external: true
